plot_wannier is parallelized
wannier-developers/wannier90 pull request #370
Opened 2021-06-19 07:04 UTC by KensukeKurita

Currently, it takes a very long time to plot the Wannier function.
This is because all k-points are calculated serially in plot_wannier() even if you use mpi.

So, I parallelized plot_wannier().
The change is simple:
- assign the computation at each k-point to multiple cores.
 `do loop_kpt = displs(my_node_id) + 1, displs(my_node_id) + counts(my_node_id)`

However, I did not change any functions in plot_main() except plot_wannier().

In my environment, when I set the number of parallelism to 10, **the time taken for plotting is about one tenth**.

2021-07-13 10:07 UTC, qiaojunfeng requested changes
Thanks! There's only one typo that needs to be fixed in `src/Makefile.2`.

2021-07-13 10:07 UTC, qiaojunfeng commented on src/Makefile.2
> +plot.o: ../plot.F90 constants.o io.o utility.o parameters.o hamiltonian.o ws_distance.o comms.o:w
there is an additional `:w`

2021-07-14 07:29 UTC, giovannipizzi commented on src/Makefile.2
> +plot.o: ../plot.F90 constants.o io.o utility.o parameters.o hamiltonian.o ws_distance.o comms.o:w
Indeed, this makes all tests fail to compile - great if this could be fixed and then we can merge the PR

2021-07-15 06:32 UTC, KensukeKurita commented on src/Makefile.2
> +plot.o: ../plot.F90 constants.o io.o utility.o parameters.o hamiltonian.o ws_distance.o comms.o:w
I appreciate your review.
I fixed the typo in `src/Makefile.2` and did recommit.

2021-07-21 12:03 UTC, giovannipizzi approved these changes
Thanks!

2021-07-21 12:03 UTC, merged